server:
  port: 8085

spring:
  application:
    name: entretien-service
  datasource:
    url: jdbc:postgresql://localhost:55432/hirehub_entretien
    username: hirehub
    password: hirehub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
