services:
  postgres:
    image: postgres:17-alpine
    container_name: hirehub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hirehub
      POSTGRES_PASSWORD: hirehub
    ports:
      - "55432:5432"
    volumes:
      - hirehub-pg-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hirehub -d hirehub_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: hirehub-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:4.3-rc-management-alpine
    container_name: hirehub-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: hirehub
      RABBITMQ_DEFAULT_PASS: hirehub
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - hirehub-rabbitmq-data:/var/lib/rabbitmq
      - hirehub-rabbitmq-logs:/var/log/rabbitmq

  #notification-service:
    #build:
      #context: .
      #dockerfile: notification-service/Dockerfile
    #container_name: hirehub-notification-service
    #restart: unless-stopped
    #depends_on:
      #postgres:
        #condition: service_healthy
      #rabbitmq:
        #condition: service_healthy
      #mailpit:
        #condition: service_started
    #environment:
      #SPRING_PROFILES_ACTIVE: docker
      #DB_HOST: postgres
      #DB_PORT: 5432
      #DB_USERNAME: hirehub
      #DB_PASSWORD: hirehub
      #RABBITMQ_HOST: rabbitmq
      #RABBITMQ_PORT: 5672
      #RABBITMQ_USERNAME: hirehub
      #RABBITMQ_PASSWORD: hirehub
      #RABBITMQ_VHOST: /
      #MAIL_HOST: mailpit
      #MAIL_PORT: 1025
      #MAIL_FROM: noreply@hirehub.com
      #EUREKA_HOST: eureka-server
      #EUREKA_PORT: 8761
    #ports:
     # - "8093:8080"
    #networks:
     # - hirehub-network
    #healthcheck:
     # test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      #interval: 30s
      #timeout: 10s
      #start_period: 40s
      #retries: 3


volumes:
  hirehub-pg-data:
  hirehub-rabbitmq-data:
  hirehub-rabbitmq-logs:

networks:
  hirehub-network:
    driver: bridge

