# =============================================================================
# install-hooks.ps1
# Script d'installation des hooks Git pour Windows PowerShell
#
# Usage :
#   Windows (PowerShell) : powershell -ExecutionPolicy Bypass -File scripts/install-hooks.ps1
#   Depuis cmd.exe : powershell -ExecutionPolicy Bypass -File scripts\install-hooks.ps1
#
# Ce script :
#   1. Cree le repertoire .git/hooks s'il n'existe pas
#   2. Copie les hooks depuis scripts/hooks/ vers .git/hooks/
#   3. Fusionne les hooks qui doivent s'executer au meme stage Git
#   4. Les rend executables (Git Bash comprend les permissions)
#   5. Affiche un rapport final
# =============================================================================

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "[*] Installation des hooks Git pour HireHub..." -ForegroundColor Cyan
Write-Host ""

# Verifier qu'on est a la racine du projet
if (-not (Test-Path ".git")) {
    Write-Host "[ERR] .git/ introuvable." -ForegroundColor Red
    Write-Host "      Ce script doit etre execute a la racine du projet." -ForegroundColor Red
    exit 1
}

if (-not (Test-Path "scripts/hooks")) {
    Write-Host "[ERR] scripts/hooks/ introuvable." -ForegroundColor Red
    exit 1
}

# Creer le repertoire .git/hooks s'il n'existe pas (normalement il existe)
$gitHooksDir = ".git\hooks"
if (-not (Test-Path $gitHooksDir)) {
    Write-Host "[DIR] Creation de .git/hooks/"
    New-Item -Path $gitHooksDir -ItemType Directory -Force | Out-Null
}

# =============================================================================
# ETAPE 1 : Installer les hooks "commit"
# =============================================================================
Write-Host "[*] Installation des hooks 'commit'..." -ForegroundColor Yellow

$preCommitPath = "$gitHooksDir\pre-commit"
$preCommitContent = ""

# Hook 1: check-sensitive-files.sh
Write-Host "    [+] Ajout de : check-sensitive-files.sh"
$checkSensitiveContent = Get-Content "scripts\hooks\check-sensitive-files.sh" -Raw
# Ajouter au contenu pre-commit
$preCommitContent += $checkSensitiveContent + "`n`n"

# Hook 2: run-checkstyle.sh
Write-Host "    [+] Ajout de : run-checkstyle.sh"
$checkstyleContent = Get-Content "scripts\hooks\run-checkstyle.sh" -Raw
$preCommitContent += $checkstyleContent + "`n"

# Ecrire le fichier pre-commit
@"
#!/bin/sh
# Auto-generated pre-commit hook combining multiple checks
# Generated by install-hooks.ps1

$preCommitContent
"@ | Set-Content -Path $preCommitPath -Encoding UTF8 -NoNewline

Write-Host "    [OK] Hook 'pre-commit' cree/mis a jour" -ForegroundColor Green

# Hook 3: commit-msg.sh
Write-Host "    [+] Ajout de : commit-msg.sh"
$commitMsgPath = "$gitHooksDir\commit-msg"
$commitMsgContent = Get-Content "scripts\hooks\commit-msg.sh" -Raw
$commitMsgContent | Set-Content -Path $commitMsgPath -Encoding UTF8 -NoNewline
Write-Host "    [OK] Hook 'commit-msg' cree/mis a jour" -ForegroundColor Green

# =============================================================================
# ETAPE 2 : Installer les hooks "push"
# =============================================================================
Write-Host ""
Write-Host "[*] Installation des hooks 'push'..." -ForegroundColor Yellow

$prePushPath = "$gitHooksDir\pre-push"
$prePushContent = ""

# Hook 1: maven-compile.sh
Write-Host "    [+] Ajout de : maven-compile.sh"
$compileContent = Get-Content "scripts\hooks\maven-compile.sh" -Raw
$prePushContent += $compileContent + "`n`n"

# Hook 2: maven-test.sh
Write-Host "    [+] Ajout de : maven-test.sh"
$testContent = Get-Content "scripts\hooks\maven-test.sh" -Raw
$prePushContent += $testContent + "`n"

# Ecrire le fichier pre-push
@"
#!/bin/sh
# Auto-generated pre-push hook combining multiple checks
# Generated by install-hooks.ps1

$prePushContent
"@ | Set-Content -Path $prePushPath -Encoding UTF8 -NoNewline

Write-Host "    [OK] Hook 'pre-push' cree/mis a jour" -ForegroundColor Green

# =============================================================================
# ETAPE 3 : Rendre les hooks executables
# =============================================================================
Write-Host ""
Write-Host "[*] Configuration des permissions..." -ForegroundColor Yellow

$hooksToMakeExecutable = @("pre-commit", "commit-msg", "pre-push")
foreach ($hook in $hooksToMakeExecutable) {
    $hookPath = "$gitHooksDir\$hook"
    if (Test-Path $hookPath) {
        # Ajouter la permission d'execution pour les utilisateurs
        $acl = Get-Acl $hookPath
        $aceObject = New-Object System.Security.AccessControl.FileSystemAccessRule(
            "BUILTIN\Users",
            "ReadAndExecute",
            "Allow"
        )
        $acl.SetAccessRule($aceObject)
        Set-Acl $hookPath $acl
        Write-Host "    [+] $hook : permissions mises a jour" -ForegroundColor Green
    }
}

# =============================================================================
# ETAPE 4 : Afficher le rapport final
# =============================================================================
Write-Host ""
Write-Host "[OK] Hooks Git installes avec succes !" -ForegroundColor Green
Write-Host ""
Write-Host "Hooks actifs :" -ForegroundColor Cyan
Write-Host ""
Write-Host "  [*] Commit hooks :" -ForegroundColor Yellow
Write-Host "      - pre-commit  : check-sensitive-files + run-checkstyle"
Write-Host "      - commit-msg  : validate Conventional Commits"
Write-Host ""
Write-Host "  [*] Push hooks :" -ForegroundColor Yellow
Write-Host "      - pre-push    : maven-compile + maven-test"
Write-Host ""
Write-Host "Tous les hooks sont executes depuis Git Bash (utilise par Git sur Windows)." -ForegroundColor Cyan
Write-Host ""
Write-Host "[*] Pour desactiver temporairement un hook :" -ForegroundColor Cyan
Write-Host "    git commit --no-verify     # Bypasse pre-commit et commit-msg"
Write-Host "    git push --no-verify       # Bypasse pre-push"
Write-Host ""
Write-Host "[*] Pour desactiver definitivement les hooks :" -ForegroundColor Cyan
Write-Host "    git config core.hooksPath /dev/null"
Write-Host ""


