#!/bin/bash
# =============================================================================
# install-hooks.sh
# Script d'installation des hooks Git pour Linux/macOS
#
# Usage :
#   Linux/macOS : ./scripts/install-hooks.sh
#   Ou : bash scripts/install-hooks.sh
#
# Ce script :
#   1. Crée le répertoire .git/hooks s'il n'existe pas
#   2. Copie les hooks depuis scripts/hooks/ vers .git/hooks/
#   3. Fusionne les hooks qui doivent s'exécuter au même stage Git
#   4. Les rend exécutables
#   5. Affiche un rapport final
# =============================================================================

set -e  # Exit on error

echo ""
echo "🔧 Installation des hooks Git pour HireHub..."
echo ""

# Vérifier qu'on est à la racine du projet
if [ ! -d ".git" ]; then
    echo "❌ Erreur : .git/ introuvable."
    echo "   Ce script doit être exécuté à la racine du projet."
    exit 1
fi

if [ ! -d "scripts/hooks" ]; then
    echo "❌ Erreur : scripts/hooks/ introuvable."
    exit 1
fi

# Créer le répertoire .git/hooks s'il n'existe pas (normalement il existe)
mkdir -p ".git/hooks"

# =============================================================================
# ÉTAPE 1 : Installer les hooks "commit"
# =============================================================================
echo "📋 Installation des hooks 'commit'..."

PRE_COMMIT_FILE=".git/hooks/pre-commit"

# Créer le header du fichier pre-commit
cat > "$PRE_COMMIT_FILE" << 'EOF'
#!/bin/sh
# Auto-generated pre-commit hook combining multiple checks
# Generated by install-hooks.sh

EOF

# Hook 1: check-sensitive-files.sh
echo "   ✓ Ajout de : check-sensitive-files.sh"
# Extraire le contenu en enlevant le shebang
tail -n +2 "scripts/hooks/check-sensitive-files.sh" >> "$PRE_COMMIT_FILE"
echo "" >> "$PRE_COMMIT_FILE"

# Hook 2: run-checkstyle.sh
echo "   ✓ Ajout de : run-checkstyle.sh"
tail -n +2 "scripts/hooks/run-checkstyle.sh" >> "$PRE_COMMIT_FILE"

chmod +x "$PRE_COMMIT_FILE"
echo "   ✅ Hook 'pre-commit' créé/mis à jour"

# Hook 3: commit-msg.sh
echo "   ✓ Ajout de : commit-msg.sh"
COMMIT_MSG_FILE=".git/hooks/commit-msg"
cp "scripts/hooks/commit-msg.sh" "$COMMIT_MSG_FILE"
chmod +x "$COMMIT_MSG_FILE"
echo "   ✅ Hook 'commit-msg' créé/mis à jour"

# =============================================================================
# ÉTAPE 2 : Installer les hooks "push"
# =============================================================================
echo ""
echo "📋 Installation des hooks 'push'..."

PRE_PUSH_FILE=".git/hooks/pre-push"

# Créer le header du fichier pre-push
cat > "$PRE_PUSH_FILE" << 'EOF'
#!/bin/sh
# Auto-generated pre-push hook combining multiple checks
# Generated by install-hooks.sh

EOF

# Hook 1: maven-compile.sh
echo "   ✓ Ajout de : maven-compile.sh"
tail -n +2 "scripts/hooks/maven-compile.sh" >> "$PRE_PUSH_FILE"
echo "" >> "$PRE_PUSH_FILE"

# Hook 2: maven-test.sh
echo "   ✓ Ajout de : maven-test.sh"
tail -n +2 "scripts/hooks/maven-test.sh" >> "$PRE_PUSH_FILE"

chmod +x "$PRE_PUSH_FILE"
echo "   ✅ Hook 'pre-push' créé/mis à jour"

# =============================================================================
# ÉTAPE 3 : Afficher le rapport final
# =============================================================================
echo ""
echo "✅ Hooks Git installés avec succès !"
echo ""
echo "Hooks actifs :"
echo ""
echo "  📋 Commit hooks :"
echo "     • pre-commit           → check-sensitive-files + run-checkstyle"
echo "     • commit-msg           → validate Conventional Commits"
echo ""
echo "  📤 Push hooks :"
echo "     • pre-push             → maven-compile + maven-test"
echo ""
echo "💡 Pour désactiver temporairement un hook :"
echo "   git commit --no-verify     # Bypasse pre-commit et commit-msg"
echo "   git push --no-verify       # Bypasse pre-push"
echo ""
echo "📝 Pour désactiver définitivement les hooks :"
echo "   git config core.hooksPath /dev/null"
echo ""

