spring:
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    from: noreply@hirehub.local
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.hirehub.email: DEBUG
    org.springframework.mail: INFO
